<a href="https://colab.research.google.com/github/IqraSiddiqui022/NLP/blob/main/nlp_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python -m spacy info


============================== Info about spaCy ==============================

spaCy version    3.7.5                         
Location         /usr/local/lib/python3.11/dist-packages/spacy
Platform         Linux-6.1.85+-x86_64-with-glibc2.35
Python version   3.11.11                       
Pipelines        en_core_web_sm (3.7.1)        



In [ ]:
 import spacy

In [ ]:
!python -m spacy download en_core_web_sm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 29.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


## **Tokenization**

- **Tokenization** is the cognitive process of **breaking text into little parts** (tokens).
1. Tokens can be **words, prison term, or even paragraphs**.
- Example:

"I love NLP! "

Tokens: ["I", "love", "NLP", "! "]

1.
    1. **Why Tokenization?**  It facilitate in processing school text efficiently for NLP tasks.

## **Iterable Objects in Python**

- Lists are iterable objects, stand for they allow iteration (looping).

### **Token Properties:**

- "didn't" → Rive into **"did"** and **"n't"**
1. "₹500" → "₹" and "500"
2. "Hello. " → "Hello" and ". "
- The Doc object supports indexing and slicing like a Python list:

print(doc[0]) # First Good Book

print(doc[:3]) # First three Scripture

In [ ]:
nlp = spacy.load('en_core_web_sm')

In [ ]:
"I love NLP!"
Tokens: ["I", "love", "NLP", "!"]


In [ ]:
for i in [1, 2, 3, 4]:
    print(i)

1
2
3
4


In [ ]:
doc = nlp("I love NLP!")

In [ ]:
print([t.text for t in doc])

['I', 'love', 'NLP', '!']


In [ ]:
print(doc[0])

I


In [ ]:
print(type(doc[0]))

<class 'spacy.tokens.token.Token'>


In [ ]:
print(doc[0:3])
print(type(doc[0:3]))

I love NLP
<class 'spacy.tokens.span.Span'>


In [ ]:
print([(t.text, t.i) for t in doc])

[('I', 0), ('love', 1), ('NLP', 2), ('!', 3)]


In [ ]:
print(doc.text)

I love NLP!


In [ ]:
print(doc[0])  # First word
print(doc[:3]) # First three words

I
I love NLP


In [ ]:
s = "He didn't want to pay $20 for this book."
doc = nlp(s)

In [ ]:
print([t.text for t in doc])

['He', 'did', "n't", 'want', 'to', 'pay', '$', '20', 'for', 'this', 'book', '.']


In [ ]:

s = """Either the well was very deep, or she fell very slowly, for she
had plenty of time as she went down to look about her and to wonder what
was going to happen next. First, she tried to look down and make out what
she was coming to, but it was too dark to see anything; then she looked at
the sides of the well, and noticed that they were filled with cupboards and
book-shelves; here and there she saw maps and pictures hung upon pegs."""

s = """Either the well was very deep, or she fell very slowly, for she
had plenty of time as she went down to look about her and to wonder what
was going to happen next. First, she tried to look down and make out what
she was coming to, but it was too dark to see anything; then she looked at
the sides of the well, and noticed that they were filled with cupboards and
book-shelves; here and there she saw maps and pictures hung upon pegs."""

doc = nlp(s)

# Look at individual sentences (there should be two 'Span' objects).
print([sent for sent in doc.sents])

[Either the well was very deep, or she fell very slowly, for she
had plenty of time as she went down to look about her and to wonder what
was going to happen next., First, she tried to look down and make out what
she was coming to, but it was too dark to see anything; then she looked at
the sides of the well, and noticed that they were filled with cupboards and
book-shelves; here and there she saw maps and pictures hung upon pegs.]


In [ ]:
#
# EXERCISE:
# 1) Tokenize the following text
# 2) Iterate through the tokens to check whether there's a currency symbol.
# 3) If there is, and the currency label is followed by a number, print
#    both the symbol and the number.
#
# Look through https://spacy.io/api/token#attributes on how to check whether
# a token is a currency symbol or a number.
#
# Expected output: "$20".
import spacy

# Load the language model
nlp2 = spacy.load('en_core_web_sm')

s = "He didn't want to pay $20 for this book."
doc = nlp2(s)

# Iterate through tokens and check for currency symbols and numbers
for token in doc:
    # Check if the token is a currency symbol using token.is_currency
    if token.is_currency:
        # Check if the next token is a number using token.like_num
        if doc[token.i + 1].like_num:
            print(token.text, doc[token.i + 1].text) # Print the symbol and number

/usr/local/lib/python3.11/dist-packages/spacy/util.py:1740: UserWarning: [W111] Jupyter notebook detected: if using `prefer_gpu()` or `require_gpu()`, include it in the same cell right before `spacy.load()` to ensure that the model is loaded on the correct device. More information: http://spacy.io/usage/v3#jupyter-notebook-gpu
  warnings.warn(Warnings.W111)


$ 20


In [ ]:
import nltk
from nltk.tokenize import TreebankWordTokenizer
s = "Let's go to N.Y.C. for the weekend."

In [ ]:
k = "He told Dr. Lovato that he was done with the tests and would post the results shortly."
doc = nlp(k)

**1. Case-Folding (Lowercasing)
Convert text to lowercase for uniformity.
Model: "NLP is Fun" → "nlp is fun"
spaCy uses token. lower_ attribute to access lowercase text.**

In [ ]:
print([t.lower_ for t in doc])

['he', 'told', 'dr.', 'lovato', 'that', 'he', 'was', 'done', 'with', 'the', 'tests', 'and', 'would', 'post', 'the', 'results', 'shortly', '.']


In [ ]:
print([t.lower_ if not t.is_sent_start else t for t in doc])

[He, 'told', 'dr.', 'lovato', 'that', 'he', 'was', 'done', 'with', 'the', 'tests', 'and', 'would', 'post', 'the', 'results', 'shortly', '.']


2. End Word Removal
Stop words are common word (for example, "the", "is", "and") that don’t carry much meaning.
spaCy has a make-in blockage word list.
Example:
token. is_stop # Returns True if a souvenir is a stop give-and-take < /div>

In [ ]:
# spaCy's default stop word list.
print(nlp.Defaults.stop_words)
print(len(nlp.Defaults.stop_words))

{'however', 'ours', 'nowhere', 'twelve', 'for', 'well', 'himself', 'must', 'about', 'who', 'yourself', 'at', 'unless', 'across', 'whereafter', 'does', 'just', 'are', 'more', 'whereas', 'did', 'itself', 'until', 'none', 'say', 'from', 'part', 'go', 'with', 'by', 'formerly', 'these', 'than', 'be', 'whole', 'under', 'around', 'after', 'here', 'fifty', 'whereby', '‘ve', 'perhaps', 'many', 'might', 'various', 'regarding', 'toward', 'latter', 'hereupon', 'move', 'herein', 'he', 'whom', 'therein', 'two', 'get', 'into', 'six', 'because', 'hers', 'and', 'sometime', 'thereby', 'been', 'can', 'this', 'therefore', "'re", 'thru', 'they', 'nobody', 'below', 'first', 'there', 'we', 'please', 'name', 'becoming', 'nine', 'will', "n't", '‘ll', 'using', 'became', 'whose', 'via', 'was', 'once', 'during', 'next', 'as', 'due', '‘d', 'less', 'whatever', 'hundred', 'my', 'n’t', 'mine', 'whither', 'top', '’d', 'your', 'its', 'other', 'alone', 'if', 'take', 'put', 'should', 'somehow', 'then', 'doing', 'nor', 'a

print([t for t in doc if not t.is_stop])

### **3. Lemmatization vs. Stemming**

Feature Stemming Lemmatization

Definition

Removes prefix & suffixes

Happen dictionary-based root word

Example

"changing" → "chang"

"changing" → "change"

Accuracy

Less precise

More accurate

Method

Rule-based

Dictionary-based

- **spaCy supports lemmatization using token. lemma_**
- **NLTK** render stem with the  **Snowball Stemmer**.

In [ ]:
[(t.text, t.lemma_) for t in doc]

[('He', 'he'),
 ('told', 'tell'),
 ('Dr.', 'Dr.'),
 ('Lovato', 'Lovato'),
 ('that', 'that'),
 ('he', 'he'),
 ('was', 'be'),
 ('done', 'do'),
 ('with', 'with'),
 ('the', 'the'),
 ('tests', 'test'),
 ('and', 'and'),
 ('would', 'would'),
 ('post', 'post'),
 ('the', 'the'),
 ('results', 'result'),
 ('shortly', 'shortly'),
 ('.', '.')]

**basic processing**

In [ ]:
from nltk.stem.snowball import SnowballStemmer
s = 'He told Dr. Lovato that he was done with the tests and would post the results shortly.'

## **Advanced Text Processing Techniques**

### **1. Part-of-Speech (POS) Tagging**

- Identifies words as **nouns, verb, adjectives, etc.**
    - Instance: "The cat posture on the mat. ""cat" → Noun
    - "sat" → Verb

In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm')
s = "John watched an old movie at the cinema."
doc = nlp(s)

/usr/local/lib/python3.11/dist-packages/spacy/util.py:1740: UserWarning: [W111] Jupyter notebook detected: if using `prefer_gpu()` or `require_gpu()`, include it in the same cell right before `spacy.load()` to ensure that the model is loaded on the correct device. More information: http://spacy.io/usage/v3#jupyter-notebook-gpu
  warnings.warn(Warnings.W111)


In [ ]:
[(t.text, t.pos_) for t in doc]

[('John', 'PROPN'),
 ('watched', 'VERB'),
 ('an', 'DET'),
 ('old', 'ADJ'),
 ('movie', 'NOUN'),
 ('at', 'ADP'),
 ('the', 'DET'),
 ('cinema', 'NOUN'),
 ('.', 'PUNCT')]

In [ ]:
spacy.explain('PROPN')

'proper noun'

In [ ]:
[(t.text, t.tag_) for t in doc]

[('John', 'NNP'),
 ('watched', 'VBD'),
 ('an', 'DT'),
 ('old', 'JJ'),
 ('movie', 'NN'),
 ('at', 'IN'),
 ('the', 'DT'),
 ('cinema', 'NN'),
 ('.', '.')]

In [ ]:
print(spacy.explain('NNP'))
print(spacy.explain('VBD'))

noun, proper singular
verb, past tense


### **2. Distinguish Entity Recognition (NER)**

- **Tell Apart entities** like names, appointment, and places.
    - Example: "Elon Musk notice Tesla in 2003. ""Elon Musk" → **Person**
    - "Tesla" → **Organization**
    - "2003" → Date
    

In [ ]:
s = "Volkswagen is developing an electric sedan which could potentially come to America next fall."
doc = nlp(s)

[(t.text, t.ent_type_) for t in doc]

[('Volkswagen', 'ORG'),
 ('is', ''),
 ('developing', ''),
 ('an', ''),
 ('electric', ''),
 ('sedan', ''),
 ('which', ''),
 ('could', ''),
 ('potentially', ''),
 ('come', ''),
 ('to', ''),
 ('America', 'GPE'),
 ('next', 'DATE'),
 ('fall', 'DATE'),
 ('.', '')]

In [ ]:
from spacy import displacy

# We need to set the 'jupyter' variable to True in order to output
# the visualization directly. Otherwise, you'll get raw HTML.
displacy.render(doc, style='ent', jupyter=True)

In [ ]:
s = "Ridley Scott directed The Martian."
doc = nlp(s)
displacy.render(doc, style='ent', jupyter=True)

In [ ]:
s = "She enrolled in the course at the university."
doc = nlp(s)

# Note the 'style' argument is assigned a 'dep' flag this time around.
displacy.render(doc, style='dep', jupyter=True)

In [ ]:
spacy.explain('nsubj')

'nominal subject'

In [ ]:
[(t.text, t.dep_) for t in doc]

[('She', 'nsubj'),
 ('enrolled', 'ROOT'),
 ('in', 'prep'),
 ('the', 'det'),
 ('course', 'pobj'),
 ('at', 'prep'),
 ('the', 'det'),
 ('university', 'pobj'),
 ('.', 'punct')]

In [ ]:
# The general Matcher is one of multiple matcher objects
# included with spaCy.
from spacy.matcher import Matcher

# We initialize the Matcher with the spaCy vocab object, which contains
# words along with their labels and entities.
matcher = Matcher(nlp.vocab)

s = "I want to book a hotel room."
doc = nlp(s)

# Patterns are expressed as an ordered sequence. Here, we're looking
# to match occurrences starting with a 'book' string followed by
# a determiner (DET) POS tag, then a noun POS tag.
# The OP key marks the match as optional in some way.

# Here, the DET POS (marked with '?') will match 0 or 1 times, and
# the NOUN POS (marked with '+') will match 1 or more times.
# See this link for more information:
# https://spacy.io/usage/rule-based-matching#quantifiers
pattern = [
  {'TEXT': 'book'},
  {'POS': 'DET', 'OP': '?'},
  {'POS': 'NOUN', 'OP': '+'},
]

# We give our pattern a label and pass it to the matcher.
matcher.add('USER_INTENT', [pattern])

# Run the matcher over the doc.
matches = matcher(doc)

# For each match, the matcher returns a tuple specifying a match id, start,
# and end of the match.
print("Matches:", [doc[start:end].text for match_id, start, end in matches])

Matches: ['book a hotel', 'book a hotel room']


Yoda's Form (Object-Subject-verb)
"You will learn NLP."

How does this work
In the interest of NLP, dependency parsing is an NLP technique for determining the structure of a sentence.  // Reorder the words based on their dependency roles (word order of an English sentence can be re-arranged if subject,verb and object plays same role

As Yoda,** tends to put objects first, so we order the sentence like this.

In [ ]:
def yodize(s: str):
  doc = nlp(s)
  for t in doc:
    if t.dep_ == "ROOT":

      # Assuming our sentence is of the form subject-verb-object, we take
      # everything after the root (likely verb) and put it in front, and
      # likewise take everything before the root, and put it after.
      seq = [doc[t.i + 1: -1].text, doc[0: t.i].text, t.text + '.']
      seq[0] = seq[0].capitalize()
      print(' '.join(seq))

In [ ]:
s = "We'll be in Osaka on Feb 13th and leave on Feb 24th."
doc = nlp(s)

In [ ]:
#
# Using the PhraseMatcher, find the start and end index of all occurrences
# of 'Caesar Augustus' and 'Roman Empire' (case-insensitive).
#
# Expected output: [(0, 2), (15, 17)]
#
from spacy.matcher import PhraseMatcher
s = "Caesar Augustus was the founder of the Roman Principate (the first phase of the Roman Empire)."
doc = nlp(s)

### **Improving bowing: N-Grams**

- **N-grams** gaining control news sequences.
    - **Deterrent Example of bigrams (n=2):**"Natural Language"
    - "Language Processing"
- In **CountVectorizer**, dress ngram_range=(1, 2) to get unigrams & bigrams.

## **Custom Tokenization in BoW**

- We can use a custom tokenizer in CountVectorizer.
- Example utilize spaCy:

vectorizer = CountVectorizer(tokenizer=spacy_tokenizer, binary=True)

bow = vectorizer. fit_transform(corpus)

- **Binary BOW** → Only computer memory **presence (1) or absence (0) of words**, not frequency.

In [ ]:
import spacy

from scipy import spatial
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [ ]:

# A corpus of sentences.
corpus = [
  "Red Bull drops hint on F1 engine.",
  "Honda exits F1, leaving F1 partner Red Bull.",
  "Hamilton eyes record eighth F1 title.",
  "Aston Martin announces sponsor."
]

In [ ]:
vectorizer = CountVectorizer()


In [ ]:
bow = vectorizer.fit_transform(corpus)


In [ ]:
# View features (tokens).
print(vectorizer.get_feature_names_out())

# View vocabulary dictionary.
vectorizer.vocabulary_

['announces' 'aston' 'bull' 'drops' 'eighth' 'engine' 'exits' 'eyes' 'f1'
 'hamilton' 'hint' 'honda' 'leaving' 'martin' 'on' 'partner' 'record'
 'red' 'sponsor' 'title']


{'red': 17,
 'bull': 2,
 'drops': 3,
 'hint': 10,
 'on': 14,
 'f1': 8,
 'engine': 5,
 'honda': 11,
 'exits': 6,
 'leaving': 12,
 'partner': 15,
 'hamilton': 9,
 'eyes': 7,
 'record': 16,
 'eighth': 4,
 'title': 19,
 'aston': 1,
 'martin': 13,
 'announces': 0,
 'sponsor': 18}

In [ ]:
print(type(bow))

<class 'scipy.sparse._csr.csr_matrix'>


In [ ]:

print(bow)

  (0, 17)	1
  (0, 2)	1
  (0, 3)	1
  (0, 10)	1
  (0, 14)	1
  (0, 8)	1
  (0, 5)	1
  (1, 17)	1
  (1, 2)	1
  (1, 8)	2
  (1, 11)	1
  (1, 6)	1
  (1, 12)	1
  (1, 15)	1
  (2, 8)	1
  (2, 9)	1
  (2, 7)	1
  (2, 16)	1
  (2, 4)	1
  (2, 19)	1
  (3, 1)	1
  (3, 13)	1
  (3, 0)	1
  (3, 18)	1


In [ ]:
# As usual, we start by importing spaCy and loading a statistical model.
nlp = spacy.load('en_core_web_sm')

# Create a tokenizer callback using spaCy under the hood. Here, we tokenize
# the passed-in text and return the tokens, filtering out punctuation.
def spacy_tokenizer(doc):
  return [t.text for t in nlp(doc) if not t.is_punct]

In [ ]:
vectorizer = CountVectorizer(tokenizer=spacy_tokenizer, lowercase=False, binary=True)
bow = vectorizer.fit_transform(corpus)

/usr/local/lib/python3.11/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [ ]:
print(vectorizer.get_feature_names_out())
vectorizer.vocabulary_

['Aston' 'Bull' 'F1' 'Hamilton' 'Honda' 'Martin' 'Red' 'announces' 'drops'
 'eighth' 'engine' 'exits' 'eyes' 'hint' 'leaving' 'on' 'partner' 'record'
 'sponsor' 'title']


{'Red': 6,
 'Bull': 1,
 'drops': 8,
 'hint': 13,
 'on': 15,
 'F1': 2,
 'engine': 10,
 'Honda': 4,
 'exits': 11,
 'leaving': 14,
 'partner': 16,
 'Hamilton': 3,
 'eyes': 12,
 'record': 17,
 'eighth': 9,
 'title': 19,
 'Aston': 0,
 'Martin': 5,
 'announces': 7,
 'sponsor': 18}

In [ ]:
print('A dense representation like we saw in the slides.')
print(bow.toarray())
print()
print('Indexing and slicing.')
print(bow[0])
print()
print(bow[0:2])

A dense representation like we saw in the slides.
[[0 1 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0]
 [0 1 1 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0]
 [0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1]
 [1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0]]

Indexing and slicing.
  (0, 6)	1
  (0, 1)	1
  (0, 8)	1
  (0, 13)	1
  (0, 15)	1
  (0, 2)	1
  (0, 10)	1

  (0, 6)	1
  (0, 1)	1
  (0, 8)	1
  (0, 13)	1
  (0, 15)	1
  (0, 2)	1
  (0, 10)	1
  (1, 6)	1
  (1, 1)	1
  (1, 2)	1
  (1, 4)	1
  (1, 11)	1
  (1, 14)	1
  (1, 16)	1


## **Cosine Similarity**

- **Measuring Rod text similarity** between documents.
- **Formula:** cos⁡(θ)=A⋅B∣∣A∣∣∣∣B∣∣\cos(\theta) = \frac{A \cdot B}{||A|| ||B||}
- **Implementation habituate scipy. spatial. distance**:
from scipy. spatial. distance importee cos
similarity = 1 - cosine(vector1, vector2)

-
    - **Applications:**Search engines
    - Recommendation systems
    - Plagiarism detection

In [ ]:
from scipy.spatial.distance import cosine

In [ ]:
# The cosine method expects array_like inputs, so we need to generate
# arrays from our sparse matrix.
doc1_vs_doc2 = 1 - spatial.distance.cosine(bow[0].toarray()[0], bow[1].toarray()[0])
doc1_vs_doc3 = 1 - spatial.distance.cosine(bow[0].toarray()[0], bow[2].toarray()[0])
doc1_vs_doc4 = 1 - spatial.distance.cosine(bow[0].toarray()[0], bow[3].toarray()[0])

print(corpus)

print(f"Doc 1 vs Doc 2: {doc1_vs_doc2}")
print(f"Doc 1 vs Doc 3: {doc1_vs_doc3}")
print(f"Doc 1 vs Doc 4: {doc1_vs_doc4}")

['Red Bull drops hint on F1 engine.', 'Honda exits F1, leaving F1 partner Red Bull.', 'Hamilton eyes record eighth F1 title.', 'Aston Martin announces sponsor.']
Doc 1 vs Doc 2: 0.4285714285714286
Doc 1 vs Doc 3: 0.15430334996209194
Doc 1 vs Doc 4: 0.0


In [ ]:
vectorizer = CountVectorizer(tokenizer=spacy_tokenizer, lowercase=False, binary=True, ngram_range=(1,2))
bigrams = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print('Number of features: {}'.format(len(vectorizer.get_feature_names_out())))
print(vectorizer.vocabulary_)

['Aston' 'Aston Martin' 'Bull' 'Bull drops' 'F1' 'F1 engine' 'F1 leaving'
 'F1 partner' 'F1 title' 'Hamilton' 'Hamilton eyes' 'Honda' 'Honda exits'
 'Martin' 'Martin announces' 'Red' 'Red Bull' 'announces'
 'announces sponsor' 'drops' 'drops hint' 'eighth' 'eighth F1' 'engine'
 'exits' 'exits F1' 'eyes' 'eyes record' 'hint' 'hint on' 'leaving'
 'leaving F1' 'on' 'on F1' 'partner' 'partner Red' 'record'
 'record eighth' 'sponsor' 'title']
Number of features: 40
{'Red': 15, 'Bull': 2, 'drops': 19, 'hint': 28, 'on': 32, 'F1': 4, 'engine': 23, 'Red Bull': 16, 'Bull drops': 3, 'drops hint': 20, 'hint on': 29, 'on F1': 33, 'F1 engine': 5, 'Honda': 11, 'exits': 24, 'leaving': 30, 'partner': 34, 'Honda exits': 12, 'exits F1': 25, 'F1 leaving': 6, 'leaving F1': 31, 'F1 partner': 7, 'partner Red': 35, 'Hamilton': 9, 'eyes': 26, 'record': 36, 'eighth': 21, 'title': 39, 'Hamilton eyes': 10, 'eyes record': 27, 'record eighth': 37, 'eighth F1': 22, 'F1 title': 8, 'Aston': 0, 'Martin': 13, 'announces

In [ ]:
# Setting n_gram range to (2, 2) generates only bigrams.
vectorizer = CountVectorizer(tokenizer=spacy_tokenizer, lowercase=False, binary=True, ngram_range=(2,2))
bigrams = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(vectorizer.vocabulary_)

['Aston Martin' 'Bull drops' 'F1 engine' 'F1 leaving' 'F1 partner'
 'F1 title' 'Hamilton eyes' 'Honda exits' 'Martin announces' 'Red Bull'
 'announces sponsor' 'drops hint' 'eighth F1' 'exits F1' 'eyes record'
 'hint on' 'leaving F1' 'on F1' 'partner Red' 'record eighth']
{'Red Bull': 9, 'Bull drops': 1, 'drops hint': 11, 'hint on': 15, 'on F1': 17, 'F1 engine': 2, 'Honda exits': 7, 'exits F1': 13, 'F1 leaving': 3, 'leaving F1': 16, 'F1 partner': 4, 'partner Red': 18, 'Hamilton eyes': 6, 'eyes record': 14, 'record eighth': 19, 'eighth F1': 12, 'F1 title': 5, 'Aston Martin': 0, 'Martin announces': 8, 'announces sponsor': 10}


## **Bag of Words (arc) Model**

- Represents **documents as numerical vectors**.
- Each row = a document, each chromatography column = a tidings count.

In [ ]:
# EXERCISE: Create a spacy_tokenizer callback which takes a string and returns
# a list of tokens (each token's text) with punctuation filtered out.
#
corpus = [
  "Students use their GPS-enabled cellphones to take birdview photographs of a land in order to find specific danger points such as rubbish heaps.",
  "Teenagers are enthusiastic about taking aerial photograph in order to study their neighbourhood.",
  "Aerial photography is a great way to identify terrestrial features that aren’t visible from the ground level, such as lake contours or river paths.",
  "During the early days of digital SLRs, Canon was pretty much the undisputed leader in CMOS image sensor technology.",
  "Syrian President Bashar al-Assad tells the US it will 'pay the price' if it strikes against Syria."
]

nlp = spacy.load('en_core_web_sm')

def spacy_tokenizer(doc):

  pass

In [ ]:
s = ["Teenagers take aerial shots of their neighbourhood using digital cameras sitting in old bottles which are launched via kites - a common toy for children living in the favelas. They then use GPS-enabled smartphones to take pictures of specific danger points - such as rubbish heaps, which can become a breeding ground for mosquitoes carrying dengue fever."]
new_bow = vectorizer.transform(s)
import numpy as np
def cos_sim(a, b):
  pass

### TF-IDF (Term Frequency-Inverse Document Frequency)

TF-IDF is a **Natural Language Processing (NLP)** term in which we use to find the importance of a word in any document over a set documents.

### **Key Features:**

- Allows the identification of **highly relevant terms** in a document
- **Reduces common** (e.g., 'the', 'is') words occurences in document.
Used for:
- Search engines (to order results by relevance)
- **Text classification** (to help in better document categorization)
- **Keyword extraction** (summarizing the important content)
- **Information retrieval & sharing**

In [ ]:
!pip install -U spacy==3.*
!python -m spacy download en_core_web_sm
!python -m spacy info


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.6/30.6 MB 58.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 90.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 88.1 MB/s eta 0:00:00
  Attempting uninstall: blis
    Found existing installation: blis 0.7.11
    Uninstalling blis-0.7.11:
      Successfully uninstalled blis-0.7.11
  Attempting uninstall: thinc
    Found existing installation: thinc 8.2.5
    Uninstalling thinc-8.2.5:
      Successfully uninstalled thinc-8.2.5
  Attempting uninstall: spacy
    Found existing installation: spacy 3.7.5
    Uninstalling spacy-3.7.5:
      Successfully uninstalled spacy-3.7.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
en-core-web-sm 3.7.1 requires spacy<3.8.0,>=3.7.2, but you have spacy 3.8.4 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12

In [ ]:
from sklearn.datasets import fetch_20newsgroups

corpus = fetch_20newsgroups(categories=['sci.space'],
                            remove=('headers', 'footers', 'quotes'))

In [ ]:
print(type(corpus))

<class 'sklearn.utils._bunch.Bunch'>


In [ ]:
# Number of posts in our dataset.
len(corpus.data)

593

In [ ]:
# Number of posts in our dataset.
len(corpus.data)

593

**Creating TF-IDF features**

In [ ]:
import spacy

In [ ]:
# Like before, if we want to use spaCy's tokenizer, we need
# to create a callback. Remember to upgrade spaCy if you need
# to (refer to beginnning of file for commentary and instructions).
nlp = spacy.load('en_core_web_sm')

# We don't need named-entity recognition nor dependency parsing for
# this so these components are disabled. This will speed up the
# pipeline. We do need part-of-speech tagging however.
unwanted_pipes = ["ner", "parser"]

# For this exercise, we'll remove punctuation and spaces (which
# includes newlines), filter for tokens consisting of alphabetic
# characters, and return the lemma (which require POS tagging).
def spacy_tokenizer(doc):
  with nlp.disable_pipes(*unwanted_pipes):
    return [t.lemma_ for t in nlp(doc) if \
            not t.is_punct and \
            not t.is_space and \
            t.is_alpha]

In [ ]:
import time
start_time = time.time()

# Example function (Replace with your actual function)
def example_function():
    return "Hello, World!"

result = example_function()  # Call a real function

end_time = time.time()
print("Execution time:", end_time - start_time, "seconds")

Execution time: 9.417533874511719e-05 seconds


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import spacy

# Like before, if we want to use spaCy's tokenizer, we need
# to create a callback. Remember to upgrade spaCy if you need
# to (refer to beginnning of file for commentary and instructions).
nlp = spacy.load('en_core_web_sm')

# We don't need named-entity recognition nor dependency parsing for
# this so these components are disabled. This will speed up the
# pipeline. We do need part-of-speech tagging however.
unwanted_pipes = ["ner", "parser"]

# For this exercise, we'll remove punctuation and spaces (which
# includes newlines), filter for tokens consisting of alphabetic
# characters, and return the lemma (which require POS tagging).
def spacy_tokenizer(doc):
  with nlp.disable_pipes(*unwanted_pipes):
    return [t.lemma_ for t in nlp(doc) if \
            not t.is_punct and \
            not t.is_space and \
            t.is_alpha]

# Use the default settings of TfidfVectorizer.
vectorizer = TfidfVectorizer(tokenizer=spacy_tokenizer)  # Define vectorizer here
features = vectorizer.fit_transform(corpus.data)

# The number of unique tokens.
print(len(vectorizer.get_feature_names_out())) # Now 'vectorizer' is accessible
print(len(vectorizer.get_feature_names_out()))

/usr/local/lib/python3.11/dist-packages/spacy/util.py:1740: UserWarning: [W111] Jupyter notebook detected: if using `prefer_gpu()` or `require_gpu()`, include it in the same cell right before `spacy.load()` to ensure that the model is loaded on the correct device. More information: http://spacy.io/usage/v3#jupyter-notebook-gpu
  warnings.warn(Warnings.W111)
/usr/local/lib/python3.11/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


9463
9463


In [ ]:


from sklearn.feature_extraction.text import TfidfVectorizer

corpus = ["This is an example sentence", "Another document here"]
vectorizer = TfidfVectorizer()
features = vectorizer.fit_transform(corpus)

print(features.shape)

(2, 8)


In [ ]:
# Transform the query into a TF-IDF vector.
query = ["lunar orbit"]
query_tfidf = vectorizer.transform(query)

In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")

def spacy_tokenizer(text):
    doc = nlp(text)
    return [token.lemma_ for token in doc if not token.is_stop and not token.is_punct]


In [ ]:

import spacy

nlp = spacy.load("en_core_web_sm")

def spacy_tokenizer(text):
    doc = nlp(text)
    return [token.lemma_ for token in doc if not token.is_stop and not token.is_punct]


In [ ]:
import numpy as np

# numpy's argsort() method returns a list of *indices* that
# would sort an array:
# https://numpy.org/doc/stable/reference/generated/numpy.argsort.html
#
# The sort is ascending, but we want the largest k cosine_similarites
# at the bottom of the sort. So we negate k, and get the last k
# entries of the indices list in reverse order. There are faster
# ways to do this using things like argpartition but this is
# more succinct.
def top_k(arr, k):
  kth_largest = (k + 1) * -1
  return np.argsort(arr)[:kth_largest:-1]

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Assuming 'features' is the TF-IDF matrix
cosine_similarities = cosine_similarity(features, features)


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Example corpus
corpus = ["This is an example sentence", "Another document is here", "This example is different"]

# Vectorizing the text
vectorizer = TfidfVectorizer()
features = vectorizer.fit_transform(corpus)

# Compute cosine similarity
cosine_similarities = cosine_similarity(features, features)


In [ ]:
def top_k(similarities, k):
    return np.argsort(similarities, axis=1)[:, -k:]  # Get indices of top k values


In [ ]:
top_related_indices = top_k(cosine_similarities, 5)
print(top_related_indices)  # Check if this prints valid indices


[[1 2 0]
 [0 2 1]
 [1 0 2]]


In [ ]:

print("Cosine Similarities:\n", cosine_similarities)
print("Top Related Indices:\n", top_related_indices)

Cosine Similarities:
 [[1.         0.10180788 0.50801465]
 [0.10180788 1.         0.12042206]
 [0.50801465 0.12042206 1.        ]]
Top Related Indices:
 [[1 2 0]
 [0 2 1]
 [1 0 2]]


In [ ]:
print(cosine_similarities[top_related_indices])

[[[0.10180788 1.         0.12042206]
  [0.50801465 0.12042206 1.        ]
  [1.         0.10180788 0.50801465]]

 [[1.         0.10180788 0.50801465]
  [0.50801465 0.12042206 1.        ]
  [0.10180788 1.         0.12042206]]

 [[0.10180788 1.         0.12042206]
  [1.         0.10180788 0.50801465]
  [0.50801465 0.12042206 1.        ]]]


In [ ]:
print("Features shape:", features.shape)
print("Query shape:", query_tfidf.shape)

Features shape: (3, 9)
Query shape: (1, 8)


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Sample corpus (your dataset)
corpus = ["This is a sample sentence", "Another example sentence", "Machine learning is powerful"]

# Initialize the vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the corpus
features = tfidf_vectorizer.fit_transform(corpus)



In [ ]:
query = "sample sentence"
query_tfidf = tfidf_vectorizer.transform([query])


In [ ]:
print("Features shape:", features.shape)
print("Query shape:", query_tfidf.shape)


Features shape: (3, 9)
Query shape: (1, 9)


In [ ]:
print(features.shape)
print(query_tfidf.shape)


(3, 9)
(1, 9)


In [ ]:
features = features.reshape(-1, 1)


In [ ]:
print(cosine_similarities.shape)
print(cosine_similarities)


(3, 3)
[[1.         0.10180788 0.50801465]
 [0.10180788 1.         0.12042206]
 [0.50801465 0.12042206 1.        ]]


In [ ]:
!pip install -U gensim==4.*

In [ ]:
import collections
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import spacy
import tensorflow as tf

from gensim.models.keyedvectors import KeyedVectors
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
!head -n 10 word2vec_model.bin

head: cannot open 'word2vec_model.bin' for reading: No such file or directory


In [ ]:
!wget "https://drive.google.com/uc?export=download&id=10gx1KcFxhVo0aWv-duCyyNe1wKZE3Mo" -O word2vec_model.bin
# Downloads the file from the given URL and saves it as 'word2vec_model.bin'.
# You need to find the actual URL of the file.

import os
print(os.path.getsize("word2vec_model.bin"))
# Now, this should work as the file is downloaded.


--2025-02-06 12:19:47--  https://drive.google.com/uc?export=download&id=10gx1KcFxhVo0aWv-duCyyNe1wKZE3Mo
Resolving drive.google.com (drive.google.com)... 142.251.179.100, 142.251.179.102, 142.251.179.139, ...
Connecting to drive.google.com (drive.google.com)|142.251.179.100|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=10gx1KcFxhVo0aWv-duCyyNe1wKZE3Mo&export=download [following]
--2025-02-06 12:19:47--  https://drive.usercontent.google.com/download?id=10gx1KcFxhVo0aWv-duCyyNe1wKZE3Mo&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 172.253.115.132, 2607:f8b0:4004:c06::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|172.253.115.132|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-02-06 12:19:48 ERROR 404: Not Found.

0


In [ ]:
embedding_file = './GoogleNews-vectors-negative300.bin.gz'

In [ ]:
!wget "https://drive.google.com/uc?export=download&id=10gx1KcFxhVo0aWv-duCyyNe1wKZE3Mo" -O word2vec_model.bin


--2025-02-06 12:19:52--  https://drive.google.com/uc?export=download&id=10gx1KcFxhVo0aWv-duCyyNe1wKZE3Mo
Resolving drive.google.com (drive.google.com)... 142.251.179.100, 142.251.179.102, 142.251.179.139, ...
Connecting to drive.google.com (drive.google.com)|142.251.179.100|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=10gx1KcFxhVo0aWv-duCyyNe1wKZE3Mo&export=download [following]
--2025-02-06 12:19:52--  https://drive.usercontent.google.com/download?id=10gx1KcFxhVo0aWv-duCyyNe1wKZE3Mo&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 172.253.115.132, 2607:f8b0:4004:c06::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|172.253.115.132|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-02-06 12:19:52 ERROR 404: Not Found.



In [ ]:
!pip install -U gensim==4.*
!wget -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz" -O word2vec_model.bin.gz
!gunzip word2vec_model.bin.gz
from gensim.models.keyedvectors import KeyedVectors

word_vectors = KeyedVectors.load

--2025-02-06 12:19:55--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 3.5.12.18, 52.217.93.102, 54.231.225.88, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|3.5.12.18|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-02-06 12:19:55 ERROR 404: Not Found.


gzip: word2vec_model.bin.gz: unexpected end of file


In [ ]:
!pip install -U gensim==4.*
!wget -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz" -O GoogleNews-vectors-negative300.bin.gz
!gunzip GoogleNews-vectors-negative300.bin.gz
from gensim.models import KeyedVectors

# Load the word vectors from the correct file
word_vectors = KeyedVectors.load_word2vec_format("GoogleNews-vectors-negative300.bin", binary=True, limit=200000)
# limit to 200k for speed

--2025-02-06 12:20:42--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 16.15.184.31, 54.231.195.160, 3.5.9.199, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|16.15.184.31|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-02-06 12:20:42 ERROR 404: Not Found.


gzip: GoogleNews-vectors-negative300.bin.gz: unexpected end of file


FileNotFoundError: [Errno 2] No such file or directory: 'GoogleNews-vectors-negative300.bin'

In [ ]:
!gdown "https://drive.google.com/file/d/1Ogx1KcfXhVo0aWv-duCyyNelWcKZE3Mo/view?usp=sharing"

/usr/local/lib/python3.11/dist-packages/gdown/parse_url.py:48: UserWarning: You specified a Google Drive link that is not the correct link to download a file. You might want to try `--fuzzy` option or the following url: https://drive.google.com/uc?id=1Ogx1KcfXhVo0aWv-duCyyNelWcKZE3Mo
  warnings.warn(
Downloading...
From: https://drive.google.com/file/d/1Ogx1KcfXhVo0aWv-duCyyNelWcKZE3Mo/view?usp=sharing
To: /content/view?usp=sharing
93.4kB [00:00, 7.33MB/s]


In [ ]:
word_vectors = KeyedVectors.load_word2vec_format(embedding_file, binary=True, limit=200000)

ValueError: not enough values to unpack (expected 2, got 0)

In [ ]:
from gensim.models.keyedvectors import KeyedVectors

word_vectors = KeyedVectors.load_word2vec_format

In [ ]:
from gensim.models import KeyedVectors

# Assuming 'embedding_file' contains the path to your word2vec file
embedding_file = './GoogleNews-vectors-negative300.bin.gz'  # Or your actual path
word_vectors = KeyedVectors.load_word2vec_format(embedding_file, binary=True, limit=200000)

# Now you can access word vectors:
pizza = word_vectors['pizza']
print(f'Vector dimension: {pizza.shape}')
print(pizza)

ValueError: not enough values to unpack (expected 2, got 0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install -U gensim==4.*
!wget -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz" -O GoogleNews-vectors-negative300.bin.gz
!gunzip GoogleNews-vectors-negative300.bin.gz
from gensim.models import KeyedVectors

# Assuming 'embedding_file' contains the path to your word2vec file
embedding_file = 'GoogleNews-vectors-negative300.bin'  # Updated file path

# Load the word vectors from the correct file
word_vectors = KeyedVectors.load_word2vec_format(embedding_file, binary=True, limit=200000)

# Now you can access word vectors:
pizza = word_vectors['pizza']
print(f'Vector dimension: {pizza.shape}')
print(pizza)

--2025-02-06 12:28:17--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.192.184, 52.217.75.158, 3.5.12.82, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.192.184|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-02-06 12:28:17 ERROR 404: Not Found.


gzip: GoogleNews-vectors-negative300.bin.gz: unexpected end of file


FileNotFoundError: [Errno 2] No such file or directory: 'GoogleNews-vectors-negative300.bin'

In [ ]:
!gdown "https://drive.google.com/file/d/1Ogx1KcfXhVo0aWv-duCyyNelWcKZE3Mo/view?usp=sharing"



/usr/local/lib/python3.11/dist-packages/gdown/parse_url.py:48: UserWarning: You specified a Google Drive link that is not the correct link to download a file. You might want to try `--fuzzy` option or the following url: https://drive.google.com/uc?id=1Ogx1KcfXhVo0aWv-duCyyNelWcKZE3Mo
  warnings.warn(
Downloading...
From: https://drive.google.com/file/d/1Ogx1KcfXhVo0aWv-duCyyNelWcKZE3Mo/view?usp=sharing
To: /content/view?usp=sharing
93.7kB [00:00, 35.9MB/s]


In [ ]:
print(word_vectors.similarity('pizza', 'tomato'))
print(word_vectors.similarity('pizza', 'sauce'))
print(word_vectors.similarity('pizza', 'cheese'))

AttributeError: 'function' object has no attribute 'similarity'

In [ ]:
try:
  word_vectors['womblyboo']
except KeyError as e:
  print(e)

TypeError: 'method' object is not subscriptable